import { router, useLocalSearchParams } from 'expo-router';
import React, { useMemo, useState } from 'react';
import { ScrollView, StyleSheet, Text } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Chip, EmptyState, JobCard, SearchField, ScreenHeader, TradeCard } from '@/components/TradeFindUI';
import { Trade, useTradeFind } from '@/context/TradeFindContext';
import { useColors } from '@/hooks/useColors';
const filters: (Trade | 'All')[] = ['All', 'Builder', 'Electrician', 'Plumber', 'Carpenter', 'Painter & Decorator', 'Handyman'];
export default function JobsScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const { currentUser, jobs, users } = useTradeFind(); const params = useLocalSearchParams<{ trade?: string }>(); const [search, setSearch] = useState(''); const [trade, setTrade] = useState<Trade | 'All'>((params.trade as Trade) || 'All'); const isTrade = currentUser?.role === 'tradesperson';
  const foundJobs = useMemo(() => jobs.filter((job) => (trade === 'All' || job.trade === trade) && (job.title + job.location + job.trade).toLowerCase().includes(search.toLowerCase())), [jobs, search, trade]); const foundTrades = useMemo(() => users.filter((user) => user.role === 'tradesperson' && (trade === 'All' || user.trade === trade) && (user.name + user.location + user.trade).toLowerCase().includes(search.toLowerCase())), [users, search, trade]);
  return <ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={{ paddingTop: insets.top + 18, paddingHorizontal: 18, paddingBottom: insets.bottom + 90 }}><ScreenHeader title={isTrade ? 'Find work' : 'Find a trade'} subtitle={isTrade ? 'Free local opportunities, matched to you' : 'Reliable professionals near you'} /><SearchField value={search} onChangeText={setSearch} placeholder="Search trades, jobs or postcodes" /><ScrollView horizontal showsHorizontalScrollIndicator={false} style={{ marginTop: 13 }}>{filters.map((item) => <Chip key={item} label={item} selected={trade === item} onPress={() => setTrade(item)} />)}</ScrollView><Text style={[styles.count, { color: colors.foreground }]}>{isTrade ? foundJobs.length : foundTrades.length} {isTrade ? 'jobs nearby' : 'tradespeople found'}</Text>{isTrade ? (foundJobs.length ? foundJobs.map((job) => <JobCard key={job.id} job={job} onPress={() => router.push({ pathname: '/job/[id]', params: { id: job.id } })} />) : <EmptyState icon="briefcase-outline" title="No jobs found" body="Try changing your trade or search terms." />) : (foundTrades.length ? foundTrades.map((user) => <TradeCard key={user.id} user={user} onPress={() => router.push({ pathname: '/trade/[id]', params: { id: user.id } })} />) : <EmptyState icon="people-outline" title="No tradespeople found" body="Try another trade or wider search area." />)}</ScrollView>;
}
const styles = StyleSheet.create({ count: { fontFamily: 'Inter_700Bold', fontSize: 15, marginTop: 24, marginBottom: 11 } });