import { Ionicons } from '@expo/vector-icons';
import React, { useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { EmptyState, ScreenHeader } from '@/components/TradeFindUI';
import { useTradeFind } from '@/context/TradeFindContext';
import { useColors } from '@/hooks/useColors';
export default function MessagesScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const { currentUser, conversations, jobs, users, sendMessage } = useTradeFind(); const [activeId, setActiveId] = useState<string | null>(null); const [text, setText] = useState(''); const active = conversations.find((item) => item.id === activeId);
  if (!conversations.length) return <View style={[styles.empty, { backgroundColor: colors.background, paddingTop: insets.top + 18 }]}><ScreenHeader title="Messages" subtitle="Stay connected through every job" /><EmptyState icon="chatbubbles-outline" title="No conversations yet" body="Your job conversations will appear here." /></View>;
  if (active) { const other = users.find((user) => active.participantIds.includes(user.id) && user.id !== currentUser?.id); const job = jobs.find((item) => item.id === active.jobId); const send = async () => { if (!text.trim()) return; await sendMessage(active.id, active.jobId, other?.id ?? 'customer-1', text); setText(''); }; return <View style={[styles.root, { backgroundColor: colors.background, paddingTop: insets.top + 18, paddingBottom: insets.bottom + 68 }]}><View style={styles.chatHeader}><Pressable onPress={() => setActiveId(null)}><Ionicons name="arrow-back" size={22} color={colors.foreground} /></Pressable><View style={{ flex: 1, marginLeft: 13 }}><Text style={[styles.name, { color: colors.foreground }]}>{other?.name ?? 'TradeFind connection'}</Text><Text style={[styles.job, { color: colors.mutedForeground }]}>{job?.title ?? 'Job conversation'}</Text></View></View><FlatList data={active.messages} keyExtractor={(item) => item.id} contentContainerStyle={styles.messages} renderItem={({ item }) => <View style={[styles.bubble, { alignSelf: item.senderId === currentUser?.id ? 'flex-end' : 'flex-start', backgroundColor: item.senderId === currentUser?.id ? colors.primary : colors.card, borderColor: colors.border }]}><Text style={{ color: item.senderId === currentUser?.id ? colors.primaryForeground : colors.foreground, fontFamily: 'Inter_400Regular', fontSize: 14, lineHeight: 20 }}>{item.text}</Text><Text style={{ color: item.senderId === currentUser?.id ? '#C4F0D1' : colors.mutedForeground, fontSize: 10, marginTop: 5 }}>{item.createdAt}</Text></View>} /><View style={[styles.composer, { backgroundColor: colors.card, borderColor: colors.border }]}><TextInput value={text} onChangeText={setText} placeholder="Write a message..." placeholderTextColor={colors.mutedForeground} style={[styles.input, { color: colors.foreground }]} /><Pressable onPress={send} style={[styles.send, { backgroundColor: colors.primary }]}><Ionicons name="arrow-up" size={19} color={colors.primaryForeground} /></Pressable></View></View>; }
  return <View style={[styles.root, { backgroundColor: colors.background, paddingTop: insets.top + 18, paddingBottom: insets.bottom + 68 }]}><ScreenHeader title="Messages" subtitle="Your conversations about jobs" /><FlatList data={conversations} keyExtractor={(item) => item.id} renderItem={({ item }) => { const other = users.find((user) => item.participantIds.includes(user.id) && user.id !== currentUser?.id); const job = jobs.find((entry) => entry.id === item.jobId); return <Pressable onPress={() => setActiveId(item.id)} style={[styles.conversation, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.avatar, { backgroundColor: colors.secondary }]}><Text style={[styles.avatarText, { color: colors.primary }]}>{(other?.name ?? 'T').slice(0, 1)}</Text></View><View style={{ flex: 1 }}><Text style={[styles.name, { color: colors.foreground }]}>{other?.name ?? 'TradeFind connection'}</Text><Text style={[styles.job, { color: colors.primary }]} numberOfLines={1}>{job?.title}</Text><Text style={[styles.preview, { color: colors.mutedForeground }]} numberOfLines={1}>{item.messages[item.messages.length - 1]?.text}</Text></View><Ionicons name="chevron-forward" size={18} color={colors.mutedForeground} /></Pressable>; }} /></View>;
}
const styles = StyleSheet.create({ root: { flex: 1, paddingHorizontal: 18 }, empty: { flex: 1, paddingHorizontal: 18 }, chatHeader: { flexDirection: 'row', alignItems: 'center', paddingBottom: 15 }, name: { fontFamily: 'Inter_700Bold', fontSize: 15 }, job: { fontFamily: 'Inter_400Regular', fontSize: 11, marginTop: 3 }, messages: { flexGrow: 1, justifyContent: 'flex-end', paddingBottom: 16, gap: 9 }, bubble: { maxWidth: '82%', borderRadius: 16, borderWidth: 1, padding: 12 }, composer: { minHeight: 56, borderRadius: 16, borderWidth: 1, flexDirection: 'row', alignItems: 'center', paddingLeft: 14, paddingRight: 8, marginBottom: 9 }, input: { flex: 1, fontFamily: 'Inter_400Regular', fontSize: 14 }, send: { width: 38, height: 38, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, conversation: { borderWidth: 1, borderRadius: 17, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 11, marginBottom: 10 }, avatar: { width: 44, height: 44, borderRadius: 15, alignItems: 'center', justifyContent: 'center' }, avatarText: { fontFamily: 'Inter_700Bold', fontSize: 19 }, preview: { fontFamily: 'Inter_400Regular', fontSize: 12, marginTop: 5 } });