import { Ionicons } from '@expo/vector-icons';
import * as ImagePicker from 'expo-image-picker';
import React, { useState } from 'react';
import { Alert, Image, Pressable, ScrollView, StyleSheet, Text } from 'react-native';
import { router } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { KeyboardAwareScrollViewCompat } from '@/components/KeyboardAwareScrollViewCompat';
import { Chip, Field, PrimaryButton, ScreenHeader } from '@/components/TradeFindUI';
import { Trade, Urgency, useTradeFind } from '@/context/TradeFindContext';
import { useColors } from '@/hooks/useColors';
const trades: Trade[] = ['Builder', 'Plasterer', 'Painter & Decorator', 'Carpenter', 'Electrician', 'Plumber', 'Roofer', 'Tiler', 'Kitchen Fitter', 'Handyman', 'Landscaper'];
export default function PostJobScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const { currentUser, createJob, useDeviceLocation } = useTradeFind(); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [location, setLocation] = useState(''); const [date, setDate] = useState(''); const [budget, setBudget] = useState(''); const [trade, setTrade] = useState<Trade>('Builder'); const [urgency, setUrgency] = useState<Urgency>('Flexible'); const [photos, setPhotos] = useState<string[]>([]);
  const addPhoto = async () => { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) return; const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ImagePicker.MediaTypeOptions.Images, allowsMultipleSelection: true, quality: 0.75 }); if (!result.canceled) setPhotos(result.assets.map((asset) => asset.uri)); }; const locate = async () => { const found = await useDeviceLocation(); if (found) setLocation(found); else Alert.alert('Location unavailable', 'Please enter a town or postcode instead.'); }; const submit = async () => { if (!title.trim() || !description.trim() || !location.trim()) { Alert.alert('Add a few more details', 'A title, description and location are needed.'); return; } await createJob({ title, description, location, trade, preferredDate: date || 'Date flexible', budget: budget || undefined, urgency, photos }); Alert.alert('Job posted', 'Your job is now live.', [{ text: 'View jobs', onPress: () => router.replace('/(tabs)/jobs') }]); };
  if (currentUser?.role === 'tradesperson') return <ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={{ paddingTop: insets.top + 30, padding: 22, paddingBottom: insets.bottom + 90 }}><Ionicons name="briefcase-outline" size={30} color={colors.primary} /><Text style={[styles.big, { color: colors.foreground }]}>Looking for work?</Text><Text style={[styles.body, { color: colors.mutedForeground }]}>Find local opportunities in the Jobs tab. Customers can post jobs here.</Text><PrimaryButton label="Find nearby jobs" icon="search" onPress={() => router.push('/(tabs)/jobs')} /></ScrollView>;
  return <KeyboardAwareScrollViewCompat bottomOffset={20} contentContainerStyle={{ paddingTop: insets.top + 18, paddingHorizontal: 18, paddingBottom: insets.bottom + 90 }} style={{ backgroundColor: colors.background }} keyboardShouldPersistTaps="handled"><ScreenHeader title="Post a job" subtitle="Tell local tradespeople what you need" /><Field label="Job title" value={title} onChangeText={setTitle} placeholder="e.g. Rewire a three-bedroom house" /><Field label="Describe the work" value={description} onChangeText={setDescription} placeholder="Include useful details" multiline /><Text style={[styles.label, { color: colors.foreground }]}>Trade required</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}>{trades.map((item) => <Chip key={item} label={item} selected={trade === item} onPress={() => setTrade(item)} />)}</ScrollView><Field label="Town or postcode" value={location} onChangeText={setLocation} placeholder="e.g. M20 or Didsbury" /><Pressable onPress={locate} style={styles.location}><Ionicons name="navigate-outline" size={16} color={colors.primary} /><Text style={[styles.locationText, { color: colors.primary }]}>Use my current location</Text></Pressable><Field label="Preferred date" value={date} onChangeText={setDate} placeholder="e.g. 24 Sep" /><Field label="Budget (optional)" value={budget} onChangeText={setBudget} placeholder="e.g. £500" /><Text style={[styles.label, { color: colors.foreground }]}>Urgency</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}>{(['ASAP', 'This week', 'Flexible'] as Urgency[]).map((item) => <Chip key={item} label={item} selected={urgency === item} onPress={() => setUrgency(item)} />)}</ScrollView><Text style={[styles.label, { color: colors.foreground, marginTop: 18 }]}>Photos</Text><Pressable onPress={addPhoto} style={[styles.photo, { backgroundColor: colors.card, borderColor: colors.border }]}><Ionicons name="camera-outline" size={22} color={colors.primary} /><Text style={[styles.photoText, { color: colors.foreground }]}>{photos.length ? 'Add more photos' : 'Add photos of the job'}</Text></Pressable>{photos.length ? <ScrollView horizontal showsHorizontalScrollIndicator={false} style={{ marginBottom: 16 }}>{photos.map((photo) => <Image key={photo} source={{ uri: photo }} style={styles.preview} />)}</ScrollView> : null}<PrimaryButton label="Post job for free" icon="arrow-forward" onPress={submit} /></KeyboardAwareScrollViewCompat>;
}
const styles = StyleSheet.create({ big: { fontFamily: 'Inter_700Bold', fontSize: 29, marginTop: 14 }, body: { fontFamily: 'Inter_400Regular', fontSize: 15, lineHeight: 23, marginTop: 9, marginBottom: 24 }, label: { fontFamily: 'Inter_600SemiBold', fontSize: 13, marginTop: 6, marginBottom: 8 }, location: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: -6, marginBottom: 14 }, locationText: { fontFamily: 'Inter_600SemiBold', fontSize: 12 }, photo: { minHeight: 60, borderRadius: 14, borderWidth: 1, borderStyle: 'dashed', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9, marginBottom: 10 }, photoText: { fontFamily: 'Inter_600SemiBold', fontSize: 13 }, preview: { width: 70, height: 70, borderRadius: 12, marginRight: 8 } });