import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import React from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { PrimaryButton, SectionTitle, Stars } from '@/components/TradeFindUI';
import { useTradeFind } from '@/context/TradeFindContext';
import { useColors } from '@/hooks/useColors';
export default function TradeProfileScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const { id } = useLocalSearchParams<{ id: string }>(); const { getUser, sendMessage } = useTradeFind(); const user = getUser(id); if (!user) return null;
  const message = async () => { await sendMessage(null, 'job-1', user.id, 'Hi, I would like to discuss a job with you.'); Alert.alert('Message sent', 'Your conversation is ready in Messages.'); };
  return <ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={{ paddingTop: insets.top + 12, paddingHorizontal: 18, paddingBottom: insets.bottom + 30 }}><Pressable onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={22} color={colors.foreground} /><Text style={[styles.backText, { color: colors.foreground }]}>Profile</Text></Pressable><View style={styles.profile}><View style={[styles.avatar, { backgroundColor: colors.secondary }]}><Text style={[styles.initial, { color: colors.primary }]}>{user.name.slice(0, 1)}</Text></View><Text style={[styles.name, { color: colors.foreground }]}>{user.name}</Text><Text style={[styles.trade, { color: colors.primary }]}>{user.trade}</Text><Text style={[styles.location, { color: colors.mutedForeground }]}>{user.location}</Text><Stars rating={user.rating} size={15} /></View><View style={[styles.stats, { borderColor: colors.border }]}><View><Text style={[styles.value, { color: colors.foreground }]}>{user.reviewCount || '—'}</Text><Text style={[styles.label, { color: colors.mutedForeground }]}>Reviews</Text></View><View><Text style={[styles.value, { color: colors.foreground }]}>15 mi</Text><Text style={[styles.label, { color: colors.mutedForeground }]}>Travel radius</Text></View><View><Text style={[styles.value, { color: colors.foreground }]}>✓</Text><Text style={[styles.label, { color: colors.mutedForeground }]}>Verified</Text></View></View><PrimaryButton label="Message" icon="chatbubble-ellipses-outline" onPress={message} /><View style={[styles.availability, { backgroundColor: colors.accent }]}><Ionicons name="calendar-outline" size={18} color={colors.primary} /><Text style={[styles.availableText, { color: colors.accentForeground }]}>{user.availability}</Text></View><SectionTitle title="About" /><Text style={[styles.bio, { color: colors.mutedForeground }]}>{user.bio}</Text><SectionTitle title="Reviews" /><View style={[styles.review, { backgroundColor: colors.card, borderColor: colors.border }]}><Stars rating={user.rating} /><Text style={[styles.reviewText, { color: colors.foreground }]}>{user.reviewCount ? 'Consistently rated highly for quality, communication and reliability.' : 'Be the first customer to leave a review.'}</Text></View><Pressable onPress={() => Alert.alert('Profile reported', 'Thanks. Our team will review this profile.')} style={styles.report}><Ionicons name="flag-outline" size={17} color={colors.mutedForeground} /><Text style={[styles.reportText, { color: colors.mutedForeground }]}>Report or block this profile</Text></Pressable></ScrollView>;
}
const styles = StyleSheet.create({ back: { flexDirection: 'row', alignItems: 'center', gap: 9, marginBottom: 20 }, backText: { fontFamily: 'Inter_600SemiBold', fontSize: 15 }, profile: { alignItems: 'center' }, avatar: { width: 92, height: 92, borderRadius: 31, alignItems: 'center', justifyContent: 'center', marginBottom: 12 }, initial: { fontFamily: 'Inter_700Bold', fontSize: 40 }, name: { fontFamily: 'Inter_700Bold', fontSize: 25 }, trade: { fontFamily: 'Inter_600SemiBold', fontSize: 14, marginTop: 4 }, location: { fontFamily: 'Inter_400Regular', fontSize: 13, marginTop: 4, marginBottom: 7 }, stats: { flexDirection: 'row', justifyContent: 'space-around', borderTopWidth: 1, borderBottomWidth: 1, paddingVertical: 16, marginVertical: 23 }, value: { fontFamily: 'Inter_700Bold', fontSize: 18, textAlign: 'center' }, label: { fontFamily: 'Inter_400Regular', fontSize: 11, marginTop: 3, textAlign: 'center' }, availability: { borderRadius: 14, padding: 13, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginTop: 12 }, availableText: { fontFamily: 'Inter_600SemiBold', fontSize: 13 }, bio: { fontFamily: 'Inter_400Regular', fontSize: 15, lineHeight: 24 }, review: { borderWidth: 1, borderRadius: 16, padding: 15 }, reviewText: { fontFamily: 'Inter_400Regular', fontSize: 13, lineHeight: 19, marginTop: 10 }, report: { flexDirection: 'row', alignItems: 'center', gap: 7, justifyContent: 'center', marginTop: 26 }, reportText: { fontFamily: 'Inter_500Medium', fontSize: 12 } });