import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Location from 'expo-location';
import React, { createContext, ReactNode, useContext, useEffect, useMemo, useState } from 'react';

export type Role = 'tradesperson' | 'customer' | 'admin';
export type Trade = 'Builder' | 'Plasterer' | 'Painter & Decorator' | 'Carpenter' | 'Electrician' | 'Plumber' | 'Roofer' | 'Tiler' | 'Kitchen Fitter' | 'Handyman' | 'Landscaper';
export type Urgency = 'ASAP' | 'This week' | 'Flexible';
export interface User { id: string; role: Role; name: string; email: string; location: string; phone?: string; trade?: Trade; bio?: string; avatar?: string; rating: number; reviewCount: number; availability: string; }
export interface Job { id: string; customerId: string; title: string; description: string; trade: Trade; location: string; preferredDate: string; budget?: string; urgency: Urgency; photos: string[]; postedAt: string; distance: string; status: 'open' | 'completed'; }
export interface Application { id: string; jobId: string; tradespersonId: string; message: string; createdAt: string; status: 'interested' | 'shortlisted' | 'declined'; }
export interface Message { id: string; senderId: string; text: string; createdAt: string; }
export interface Conversation { id: string; jobId: string; participantIds: string[]; messages: Message[]; }
export interface Review { id: string; jobId: string; reviewerId: string; recipientId: string; rating: number; comment: string; createdAt: string; }

const KEY = 'tradefind-state-v1';
const makeId = (prefix: string) => prefix + '-' + Date.now().toString(36) + Math.random().toString(36).slice(2, 7);
const users: User[] = [
  { id: 'tradesperson-1', role: 'tradesperson', name: 'Mason & Sons', email: 'mason@example.com', location: 'Manchester, M20', phone: '07700 900123', trade: 'Builder', bio: 'Reliable building team specialising in extensions, renovations and structural work.', rating: 4.9, reviewCount: 38, availability: 'Available this week' },
  { id: 'tradesperson-2', role: 'tradesperson', name: 'North West Electrics', email: 'electrics@example.com', location: 'Stockport, SK3', trade: 'Electrician', bio: 'Certified domestic electrician. Fast callouts and neat, fully tested installations.', rating: 4.8, reviewCount: 24, availability: 'Available from Monday' },
  { id: 'tradesperson-3', role: 'tradesperson', name: 'Oak & Grain Joinery', email: 'oak@example.com', location: 'Altrincham, WA14', trade: 'Carpenter', bio: 'Bespoke carpentry, fitted storage and thoughtful finish work.', rating: 5, reviewCount: 19, availability: 'Taking bookings' },
  { id: 'customer-1', role: 'customer', name: 'Sarah Mitchell', email: 'sarah@example.com', location: 'Didsbury, M20', rating: 4.7, reviewCount: 6, availability: 'Active customer' },
];
const jobs: Job[] = [
  { id: 'job-1', customerId: 'customer-1', title: 'Kitchen wall removal and steel beam', description: 'We are opening up the kitchen and need a builder to remove a supporting wall and coordinate the steel installation. Plans available.', trade: 'Builder', location: 'Didsbury, Manchester', preferredDate: '18 Sep 2026', budget: '£2,000–£3,500', urgency: 'This week', photos: [], postedAt: 'Posted 2h ago', distance: '1.8 miles', status: 'open' },
  { id: 'job-2', customerId: 'customer-1', title: 'Install outdoor lighting', description: 'Six wall lights and two patio sockets to be installed around a rear extension.', trade: 'Electrician', location: 'Chorlton, Manchester', preferredDate: '22 Sep 2026', budget: '£450–£700', urgency: 'Flexible', photos: [], postedAt: 'Posted yesterday', distance: '3.4 miles', status: 'open' },
  { id: 'job-3', customerId: 'customer-1', title: 'Repair and repaint garden room', description: 'Small timber garden room needs two boards replacing, prep and a full exterior repaint.', trade: 'Painter & Decorator', location: 'Sale, Greater Manchester', preferredDate: 'ASAP', budget: '£300–£500', urgency: 'ASAP', photos: [], postedAt: 'Posted 2 days ago', distance: '5.2 miles', status: 'open' },
];
const applications: Application[] = [{ id: 'application-1', jobId: 'job-1', tradespersonId: 'tradesperson-1', message: 'We can visit tomorrow to look at the plans and provide a firm quote.', createdAt: 'Today, 09:42', status: 'interested' }];
const conversations: Conversation[] = [{ id: 'conversation-1', jobId: 'job-1', participantIds: ['customer-1', 'tradesperson-1'], messages: [{ id: 'message-1', senderId: 'customer-1', text: 'Hi, thanks for expressing interest. Are you free to visit this week?', createdAt: '09:48' }, { id: 'message-2', senderId: 'tradesperson-1', text: 'Yes, I can pop over tomorrow afternoon.', createdAt: '09:55' }] }];
type State = { users: User[]; jobs: Job[]; applications: Application[]; conversations: Conversation[]; reviews: Review[]; currentUserId: string | null };
interface Value extends State { loading: boolean; currentUser: User | null; signInAs: (role: Role, name: string) => Promise<void>; signOut: () => Promise<void>; createJob: (job: Omit<Job, 'id' | 'customerId' | 'postedAt' | 'distance' | 'status'>) => Promise<void>; expressInterest: (jobId: string, message: string) => Promise<void>; sendMessage: (conversationId: string | null, jobId: string, recipientId: string, text: string) => Promise<void>; addReview: (jobId: string, recipientId: string, rating: number, comment: string) => Promise<void>; updateProfile: (patch: Partial<User>) => Promise<void>; getUser: (id: string) => User | undefined; getJob: (id: string) => Job | undefined; useDeviceLocation: () => Promise<string | null>; }
const Context = createContext<Value | null>(null);

export function TradeFindProvider({ children }: { children: ReactNode }) {
  const [state, setState] = useState<State>({ users, jobs, applications, conversations, reviews: [], currentUserId: null });
  const [loading, setLoading] = useState(true);
  useEffect(() => { AsyncStorage.getItem(KEY).then((raw) => { if (raw) { try { setState(JSON.parse(raw) as State); } catch { /* keep seed state */ } } setLoading(false); }); }, []);
  useEffect(() => { if (!loading) AsyncStorage.setItem(KEY, JSON.stringify(state)); }, [state, loading]);
  const currentUser = state.users.find((user) => user.id === state.currentUserId) ?? null;
  const signInAs = async (role: Role, name: string) => { const user: User = { id: makeId('user'), role, name: name.trim() || (role === 'tradesperson' ? 'New tradesperson' : 'New customer'), email: 'you@tradefind.app', location: 'Manchester, UK', trade: role === 'tradesperson' ? 'Handyman' : undefined, bio: role === 'tradesperson' ? 'Tell customers about your experience and the work you do.' : undefined, rating: 0, reviewCount: 0, availability: role === 'tradesperson' ? 'Set your availability' : 'Active customer' }; setState((prev) => ({ ...prev, users: [...prev.users, user], currentUserId: user.id })); };
  const signOut = async () => setState((prev) => ({ ...prev, currentUserId: null }));
  const createJob = async (input: Omit<Job, 'id' | 'customerId' | 'postedAt' | 'distance' | 'status'>) => { const job: Job = { ...input, id: makeId('job'), customerId: state.currentUserId ?? 'customer-1', postedAt: 'Posted just now', distance: 'Near you', status: 'open' }; setState((prev) => ({ ...prev, jobs: [job, ...prev.jobs] })); };
  const expressInterest = async (jobId: string, message: string) => { if (!state.currentUserId) return; setState((prev) => ({ ...prev, applications: [{ id: makeId('application'), jobId, tradespersonId: state.currentUserId!, message, createdAt: 'Just now', status: 'interested' }, ...prev.applications] })); };
  const sendMessage = async (conversationId: string | null, jobId: string, recipientId: string, text: string) => { if (!state.currentUserId || !text.trim()) return; const message: Message = { id: makeId('message'), senderId: state.currentUserId, text: text.trim(), createdAt: 'Just now' }; setState((prev) => { const existing = conversationId ? prev.conversations.find((item) => item.id === conversationId) : prev.conversations.find((item) => item.jobId === jobId && item.participantIds.includes(state.currentUserId!)); if (existing) return { ...prev, conversations: prev.conversations.map((item) => item.id === existing.id ? { ...item, messages: [...item.messages, message] } : item) }; return { ...prev, conversations: [{ id: makeId('conversation'), jobId, participantIds: [state.currentUserId!, recipientId], messages: [message] }, ...prev.conversations] }; }); };
  const addReview = async (jobId: string, recipientId: string, rating: number, comment: string) => { if (!state.currentUserId) return; setState((prev) => ({ ...prev, reviews: [{ id: makeId('review'), jobId, reviewerId: state.currentUserId!, recipientId, rating, comment, createdAt: 'Just now' }, ...prev.reviews], users: prev.users.map((user) => user.id === recipientId ? { ...user, rating: user.reviewCount ? Number(((user.rating * user.reviewCount + rating) / (user.reviewCount + 1)).toFixed(1)) : rating, reviewCount: user.reviewCount + 1 } : user) })); };
  const updateProfile = async (patch: Partial<User>) => { if (!state.currentUserId) return; setState((prev) => ({ ...prev, users: prev.users.map((user) => user.id === prev.currentUserId ? { ...user, ...patch } : user) })); };
  const useDeviceLocation = async () => { try { const permission = await Location.requestForegroundPermissionsAsync(); if (permission.status !== 'granted') return null; const position = await Location.getCurrentPositionAsync({}); const place = (await Location.reverseGeocodeAsync({ latitude: position.coords.latitude, longitude: position.coords.longitude }))[0]; return [place?.district, place?.city, place?.postalCode].filter(Boolean).join(', ') || 'Location found'; } catch { return null; } };
  const value = useMemo<Value>(() => ({ ...state, loading, currentUser, signInAs, signOut, createJob, expressInterest, sendMessage, addReview, updateProfile, getUser: (id) => state.users.find((user) => user.id === id), getJob: (id) => state.jobs.find((job) => job.id === id), useDeviceLocation }), [state, loading, currentUser]);
  return <Context.Provider value={value}>{children}</Context.Provider>;
}
export function useTradeFind() { const value = useContext(Context); if (!value) throw new Error('useTradeFind must be used within TradeFindProvider'); return value; }