import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import React from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { ScreenHeader } from '@/components/TradeFindUI';
import { useTradeFind } from '@/context/TradeFindContext';
import { useColors } from '@/hooks/useColors';
export default function AdminScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const { users, jobs } = useTradeFind(); return <ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={{ paddingTop: insets.top + 18, paddingHorizontal: 18, paddingBottom: insets.bottom + 30 }}><Pressable onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={22} color={colors.foreground} /><Text style={[styles.backText, { color: colors.foreground }]}>Back to profile</Text></Pressable><ScreenHeader title="Admin" subtitle="Keep the marketplace safe and useful" /><View style={styles.stats}>{[['Users', users.length, 'people-outline'], ['Live jobs', jobs.length, 'briefcase-outline'], ['Reports', 0, 'flag-outline']].map(([label, value, icon]) => <View key={String(label)} style={[styles.stat, { backgroundColor: colors.card, borderColor: colors.border }]}><Ionicons name={icon as keyof typeof Ionicons.glyphMap} size={20} color={colors.primary} /><Text style={[styles.value, { color: colors.foreground }]}>{value}</Text><Text style={[styles.label, { color: colors.mutedForeground }]}>{label}</Text></View>)}</View><Text style={[styles.section, { color: colors.foreground }]}>Moderation queue</Text><View style={[styles.queue, { backgroundColor: colors.card, borderColor: colors.border }]}><Pressable onPress={() => Alert.alert('No reports', 'There are no reported items right now.')} style={styles.row}><Ionicons name="flag-outline" size={20} color={colors.primary} /><Text style={[styles.rowText, { color: colors.foreground }]}>Reported content</Text><Ionicons name="chevron-forward" size={18} color={colors.mutedForeground} /></Pressable><Pressable onPress={() => Alert.alert('Category manager', 'Trade categories are ready to be managed here.')} style={styles.row}><Ionicons name="list-outline" size={20} color={colors.primary} /><Text style={[styles.rowText, { color: colors.foreground }]}>Trade categories</Text><Ionicons name="chevron-forward" size={18} color={colors.mutedForeground} /></Pressable></View><Text style={[styles.section, { color: colors.foreground }]}>Recent users</Text>{users.slice(0, 5).map((user) => <View key={user.id} style={[styles.user, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.userIcon, { backgroundColor: colors.secondary }]}><Text style={[styles.initial, { color: colors.primary }]}>{user.name.slice(0, 1)}</Text></View><View style={{ flex: 1 }}><Text style={[styles.userName, { color: colors.foreground }]}>{user.name}</Text><Text style={[styles.userRole, { color: colors.mutedForeground }]}>{user.role} · {user.location}</Text></View><Ionicons name="ellipsis-horizontal" size={19} color={colors.mutedForeground} /></View>)}</ScrollView>;
}
const styles = StyleSheet.create({ back: { flexDirection: 'row', alignItems: 'center', gap: 9, marginBottom: 22 }, backText: { fontFamily: 'Inter_600SemiBold', fontSize: 15 }, stats: { flexDirection: 'row', gap: 8 }, stat: { flex: 1, borderWidth: 1, borderRadius: 16, padding: 13 }, value: { fontFamily: 'Inter_700Bold', fontSize: 23, marginTop: 11 }, label: { fontFamily: 'Inter_400Regular', fontSize: 11, marginTop: 2 }, section: { fontFamily: 'Inter_700Bold', fontSize: 18, marginTop: 26, marginBottom: 11 }, queue: { borderWidth: 1, borderRadius: 17, paddingHorizontal: 14 }, row: { minHeight: 60, flexDirection: 'row', alignItems: 'center', gap: 12, borderBottomWidth: 1, borderBottomColor: '#E1E9E2' }, rowText: { flex: 1, fontFamily: 'Inter_700Bold', fontSize: 14 }, user: { borderWidth: 1, borderRadius: 16, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8 }, userIcon: { width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, initial: { fontFamily: 'Inter_700Bold', fontSize: 17 }, userName: { fontFamily: 'Inter_700Bold', fontSize: 14 }, userRole: { fontFamily: 'Inter_400Regular', fontSize: 12, marginTop: 4 } });