import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import React, { useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { BrandMark, Field, PrimaryButton } from '@/components/TradeFindUI';
import { Role, useTradeFind } from '@/context/TradeFindContext';
import { useColors } from '@/hooks/useColors';

export default function WelcomeScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const { loading, currentUser, signInAs } = useTradeFind(); const [name, setName] = useState('');
  if (loading) return <View style={[styles.loading, { backgroundColor: colors.background }]}><ActivityIndicator color={colors.primary} /></View>;
  if (currentUser) { router.replace('/(tabs)'); return null; }
  const enter = async (role: Role) => { await signInAs(role, name); router.replace(role === 'admin' ? '/admin' : '/(tabs)'); };
  return <KeyboardAvoidingView style={[styles.root, { backgroundColor: colors.background }]} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={[styles.content, { paddingTop: insets.top + 22, paddingBottom: insets.bottom + 24 }]} keyboardShouldPersistTaps="handled"><BrandMark /><View style={styles.hero}><View style={[styles.badge, { backgroundColor: colors.accent }]}><Ionicons name="shield-checkmark" size={15} color={colors.primary} /><Text style={[styles.badgeText, { color: colors.accentForeground }]}>Trusted UK trades marketplace</Text></View><Text style={[styles.heroTitle, { color: colors.foreground }]}>Find work.</Text><Text style={[styles.heroTitle, { color: colors.foreground }]}>Find trades.</Text><Text style={[styles.heroTitle, { color: colors.foreground }]}>Get it done.</Text><Text style={[styles.heroBody, { color: colors.mutedForeground }]}>TradeFind connects reliable tradespeople with customers who need the job done right.</Text></View><View style={[styles.valueCard, { backgroundColor: colors.charcoal }]}><View style={styles.valueIcon}><Ionicons name="flash" size={20} color={colors.charcoal} /></View><View style={{ flex: 1 }}><Text style={styles.valueTitle}>Free for tradespeople</Text><Text style={styles.valueBody}>Browse nearby work and express interest without paywalls.</Text></View></View><Field label="What should we call you?" value={name} onChangeText={setName} placeholder="Your name or business name" /><Text style={[styles.roleLabel, { color: colors.foreground }]}>I’m joining as a...</Text><View style={styles.roleRow}><Pressable onPress={() => enter('tradesperson')} style={[styles.roleCard, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.roleIcon, { backgroundColor: colors.accent }]}><Ionicons name="construct" size={22} color={colors.primary} /></View><Text style={[styles.roleTitle, { color: colors.foreground }]}>Tradesperson</Text><Text style={[styles.roleBody, { color: colors.mutedForeground }]}>Find local jobs</Text></Pressable><Pressable onPress={() => enter('customer')} style={[styles.roleCard, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.roleIcon, { backgroundColor: colors.secondary }]}><Ionicons name="home" size={22} color={colors.primary} /></View><Text style={[styles.roleTitle, { color: colors.foreground }]}>Customer</Text><Text style={[styles.roleBody, { color: colors.mutedForeground }]}>Post a job</Text></Pressable></View><Pressable onPress={() => enter('admin')} style={styles.ownerAccess}><Ionicons name="shield-checkmark-outline" size={16} color={colors.primary} /><Text style={[styles.ownerText, { color: colors.primary }]}>Owner / Admin access</Text></Pressable><PrimaryButton label="Explore TradeFind" icon="arrow-forward" onPress={() => enter('customer')} /></ScrollView></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ root: { flex: 1 }, loading: { flex: 1, alignItems: 'center', justifyContent: 'center' }, content: { paddingHorizontal: 22 }, hero: { marginTop: 58, marginBottom: 25 }, badge: { alignSelf: 'flex-start', borderRadius: 100, paddingHorizontal: 11, paddingVertical: 7, flexDirection: 'row', alignItems: 'center', gap: 6 }, badgeText: { fontFamily: 'Inter_600SemiBold', fontSize: 11 }, heroTitle: { fontFamily: 'Inter_700Bold', fontSize: 42, lineHeight: 44, letterSpacing: -1.6 }, heroBody: { fontFamily: 'Inter_400Regular', fontSize: 16, lineHeight: 24, marginTop: 15 }, valueCard: { borderRadius: 18, padding: 17, flexDirection: 'row', alignItems: 'center', gap: 13, marginBottom: 24 }, valueIcon: { width: 40, height: 40, borderRadius: 13, backgroundColor: '#B7F1C9', alignItems: 'center', justifyContent: 'center' }, valueTitle: { color: '#FFFFFF', fontFamily: 'Inter_700Bold', fontSize: 14 }, valueBody: { color: '#B9C9BE', fontFamily: 'Inter_400Regular', fontSize: 12, lineHeight: 18, marginTop: 3 }, roleLabel: { fontFamily: 'Inter_700Bold', fontSize: 15, marginBottom: 10 }, roleRow: { flexDirection: 'row', gap: 11, marginBottom: 12 }, roleCard: { flex: 1, borderWidth: 1, borderRadius: 17, padding: 14 }, roleIcon: { width: 41, height: 41, borderRadius: 13, alignItems: 'center', justifyContent: 'center', marginBottom: 13 }, roleTitle: { fontFamily: 'Inter_700Bold', fontSize: 15 }, roleBody: { fontFamily: 'Inter_400Regular', fontSize: 12, marginTop: 4 }, ownerAccess: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, paddingVertical: 12, marginBottom: 8 }, ownerText: { fontFamily: 'Inter_600SemiBold', fontSize: 13 } });