import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import React from 'react';
import { Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { ScreenHeader } from '@/components/TradeFindUI';
import { useColors } from '@/hooks/useColors';
export default function SettingsScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); return <ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={{ paddingTop: insets.top + 18, paddingHorizontal: 18, paddingBottom: insets.bottom + 30 }}><Pressable onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={22} color={colors.foreground} /><Text style={[styles.backText, { color: colors.foreground }]}>Settings</Text></Pressable><ScreenHeader title="Account settings" subtitle="Control how TradeFind works for you" /><View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}>{['Job alerts', 'Message notifications', 'Location matching'].map((item) => <View key={item} style={styles.row}><View style={{ flex: 1 }}><Text style={[styles.title, { color: colors.foreground }]}>{item}</Text><Text style={[styles.body, { color: colors.mutedForeground }]}>{item === 'Job alerts' ? 'Get notified about matching local jobs' : item === 'Message notifications' ? 'Know when someone replies' : 'Use your area to improve results'}</Text></View><Switch value trackColor={{ false: colors.border, true: colors.accent }} thumbColor={colors.primary} /></View>)}</View><View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border, marginTop: 13 }]}>{['Terms and community rules', 'Privacy', 'Help centre'].map((item, index) => <Pressable key={item} style={styles.action}><Ionicons name={index === 0 ? 'document-text-outline' : index === 1 ? 'lock-closed-outline' : 'help-circle-outline'} size={19} color={colors.foreground} /><Text style={[styles.actionText, { color: colors.foreground }]}>{item}</Text><Ionicons name="chevron-forward" size={18} color={colors.mutedForeground} /></Pressable>)}</View></ScrollView>;
}
const styles = StyleSheet.create({ back: { flexDirection: 'row', alignItems: 'center', gap: 9, marginBottom: 22 }, backText: { fontFamily: 'Inter_600SemiBold', fontSize: 15 }, card: { borderWidth: 1, borderRadius: 17, paddingHorizontal: 15 }, row: { minHeight: 75, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#E1E9E2' }, title: { fontFamily: 'Inter_700Bold', fontSize: 14 }, body: { fontFamily: 'Inter_400Regular', fontSize: 12, marginTop: 4 }, action: { minHeight: 56, flexDirection: 'row', alignItems: 'center', gap: 11, borderBottomWidth: 1, borderBottomColor: '#E1E9E2' }, actionText: { flex: 1, fontFamily: 'Inter_600SemiBold', fontSize: 14 } });